### PR TITLE
Testing

### PR DESCRIPTION
**Pull request by mntrskl**

### CODE REVIEW

**Comment by aister** [comment]
if you want to make your own bot, don't do Pull request lol

**Comment by mntrskl** [comment]
My bad, I was trying to do the exact opposite, repo management not really
my thing. Apologies for taking your time and great bot btw, what I was
mostly interested in was the fgo gacha sim which imho yours is a great
approach.

**Comment by aister** [comment]
really? I found it kinda messy tbh

**Comment by mntrskl** [comment]
of course there's room for improvement (that would be a pull request
occasion i believe) but as image manipulation goes and having some public
data (many bots out there are using nobuDB) i do think it beats doing some
web scraping from the wiki fandom or gamepress to grab images, names,
rates, etc... also i believe there's no api developed to simulate rolls (or
at least that i know of).

anyways... sorry again for that XD, will keep leveling my edmond dantes
right now and if by some chance i find something that would be truly
helpful then i will do a new pull request =)

**Comment by aister** [comment]
it requires a lot of maintenance tho, atm both the fgo servant database as well as item database is highly outdated

**Comment by mntrskl** [comment]
If it helps, in the coming days I could fork/update some of that, was kinda
wondering what to spend my free time on XD.

btw just as a suggestion you could use some nicer fonts on the "web part" XD


And if get around scraping some other site about fgo info and making some
api, i will let you know, of course if this in anyway of help =)

**Pull request closed without merging**
